name: bayestme_spatial_expression
description: Detect spatial differential expression patterns
keywords:
  - spatial_transcriptomics
  - spatial
  - visium
tools:
  - spatial_expression:
      description: |
        Detect spatial differential expression patterns
      homepage: https://bayestme.readthedocs.io/en/latest/command_line_interface.html#spatial-expression
      documentation: https://bayestme.readthedocs.io/en/latest/command_line_interface.html#spatial-expression
      doi: 10.1016/j.cels.2023.06.003
      licence: []
      args_id: "$args"
  - plot_spatial_expression:
      description:
        Plot spatial differential expression results
      homepage: https://bayestme.readthedocs.io/en/latest/command_line_interface.html#plot-spatial-expression
      documentation: https://bayestme.readthedocs.io/en/latest/command_line_interface.html#plot-spatial-expression
      doi: 10.1016/j.cels.2023.06.003
      licence: []
      args_id: "$args2"
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - adata:
      type: file
      description: |
        Anndata archive file (.h5ad) as documented at
        https://bayestme.readthedocs.io/en/latest/data_format.html#input-format
  - deconvolution_samples:
      type: file
      description: |
        Samples from the deconvolution model posterior distribution

output:
  - sde_samples:
      type: file
      description: Samples from the SDE model posterior distribution
      pattern: "sde_samples.h5"
  - plots:
      type: file
      description: Spatial differential expression plots, will not be emitted if no significant results.
      pattern: "plots/*"
      optional: true
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@jeffquinn-msk"
