name: Nextflow Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# Cancel if a newer run is started
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pytest:
    runs-on: ubuntu-20.04
    name: pytest

    env:
      NXF_ANSI_LOG: false

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip pytest-workflow cryptography

      - name: Setup Nextflow
        uses: nf-core/setup-nextflow@v1

      # Test the module
      - name: Run pytest-workflow
        working-directory: ./nextflow
        # only use one thread for pytest-workflow to avoid race condition on conda cache.
        run: TMPDIR=~ PROFILE=${{ matrix.profile }} pytest  --symlink --kwdof --git-aware --color=yes
