name: Python Unittests
on:
  pull_request: { }
  push: { branches: main }

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          version: "~= 23.1"
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
  test:
    needs:
      - lint
      - docs
    name: Run python unittests in docker
    runs-on: ubuntu-latest
    container:
      image: jeffquinnmsk/bayestme:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run tests
      run: make python-unittest
